name: triviabattle
description: Programerski kviz aplikacija s Firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0
  connectivity_plus: ^4.0.1

  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  http: ^1.1.0
  
  # UI & State
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon1.png
  adaptive_icon_background: "#0F2027"
  adaptive_icon_foreground: assets/icon/app_icon1.png
